// Fictional collection data, authorized by the user for this demo storefront.
const fullSizes = ['XS', 'S', 'M', 'L', 'XL'];
const graphic = (id, name, price, description) => ({id, name, title: `Футболка ${name}`, price, description, image: `assets/${id}.jpg`, sizes: [...fullSizes], color: 'Чёрный', material: '100% хлопок · 240 г/м²', fit: 'Oversize / унисекс', category: 'graphic'});
export const products = [
  graphic('orbit', 'ORBIT', 4900, 'Белая фигура и орбитальный знак. Прямой свободный силуэт, спущенное плечо и плотный хлопок.'),
  graphic('float', 'FLOAT', 4900, 'Фотографический принт с фигурой в движении и каллиграфией picloms. Свободная посадка.'),
  graphic('muse', 'MUSE', 4900, 'Портретная композиция и крупный wordmark на чёрном фоне. Плотный хлопок и прямой крой.'),
  graphic('chorus', 'CHORUS', 5400, 'Панорамная графика с несколькими фигурами. Свободный силуэт и широкая линия плеча.'),
  {id:'veil',name:'VEIL',title:'Брюки VEIL',price:12900,description:'Синий деним под длинной чёрной панелью. Два слоя движутся отдельно и меняют силуэт на каждом шаге.',image:'assets/veil.png',sizes:[...fullSizes],color:'Синий / чёрный',material:'Деним: 100% хлопок; панель: 65% полиэстер, 35% вискоза',fit:'Широкие / многослойные',category:'bottom'},
  {id:'fold',name:'FOLD',title:'Брюки FOLD',price:11900,description:'Чёрные широкие брюки с плиссированным поясом на запах. Складки собирают объём вокруг талии и раскрываются в движении.',image:'assets/fold.png',sizes:[...fullSizes],color:'Чёрный',material:'65% полиэстер, 35% вискоза',fit:'Широкие / высокая посадка',category:'bottom'},
  {id:'feral',name:'FERAL',title:'Бомбер FERAL',price:24900,description:'Объёмный чёрный бомбер с отделкой коричневым искусственным мехом. Контраст гладкой поверхности и длинного ворса.',image:'assets/feral.png',sizes:['S','M','L','XL'],color:'Чёрный / коричневый',material:'Основа: 100% полиамид; искусственный мех: 100% полиэстер',fit:'Объёмный / укороченный',category:'top'},
  {id:'axis',name:'AXIS',title:'Худи AXIS',price:13900,description:'Удлинённое худи на молнии. Серебристые люверсы задают вертикальный ритм, глубокий капюшон обрамляет лицо.',image:'assets/axis.png',sizes:['S','M','L','XL'],color:'Чёрный',material:'80% хлопок, 20% полиэстер',fit:'Удлинённый / свободный',category:'top'},
  {id:'tartan',name:'TARTAN',title:'Пояс TARTAN',price:6900,description:'Асимметричный пояс на запах в красно-чёрную клетку. Длинный свободный край добавляет слой поверх брюк или юбки.',image:'assets/tartan.png',sizes:['ONE SIZE'],color:'Красный / чёрный',material:'65% полиэстер, 35% вискоза',fit:'Регулируемый / на запах',category:'accessories'},
  {id:'void',name:'VOID',title:'Футболка VOID',price:5900,description:'Чистый чёрный объём и серебристые заклёпки у нижнего края. Минимум графики, внимание к пропорциям.',image:'assets/void.png',sizes:[...fullSizes],color:'Чёрный',material:'100% хлопок · 260 г/м²',fit:'Oversize / спущенное плечо',category:'top'},
  {id:'plume',name:'PLUME',title:'Юбка PLUME',price:14900,description:'Чёрная юбка с длинным ворсом искусственного меха. Мягкая фактура делает строгий силуэт подвижным.',image:'assets/plume.png',sizes:['XS','S','M','L'],color:'Чёрный',material:'Искусственный мех и подкладка: 100% полиэстер',fit:'Прямая / средняя посадка',category:'bottom'},
  {id:'slate',name:'SLATE',title:'Жакет SLATE',price:18900,description:'Укороченный чёрный жакет с чёткой линией плеча. Собранный верх и свободный низ создают новые пропорции.',image:'assets/slate.png',sizes:['XS','S','M','L','XL'],color:'Чёрный',material:'68% полиэстер, 30% вискоза, 2% эластан',fit:'Укороченный / структурный',category:'top'},
{"id":"patch","name":"PATCH","title":"Шорты PATCH","price":9900,"category":"bottom","color":"Синий","material":"100% хлопок","fit":"Широкие / до колена","description":"Деним разных оттенков, открытые швы и объёмные карманы.","image":"assets/patch.png","sizes":["XS","S","M","L","XL"]},
{"id":"halo","name":"HALO","title":"Панама HALO","price":7900,"category":"accessories","color":"Коричневый","material":"Искусственный мех: 100% полиэстер","fit":"ONE SIZE","description":"Длинный ворс и мягкая объёмная форма.","image":"assets/halo.png","sizes":["ONE SIZE"]},
{"id":"trace","name":"TRACE","title":"Топ TRACE","price":6900,"category":"top","color":"Чёрный","material":"95% хлопок, 5% эластан","fit":"Прилегающий / укороченный","description":"Асимметричная горловина и необработанный край.","image":"assets/trace.png","sizes":["XS","S","M","L","XL"]},
{"id":"shroud","name":"SHROUD","title":"Платок SHROUD","price":4900,"category":"accessories","color":"Синий","material":"100% хлопок","fit":"ONE SIZE","description":"Скульптурный деним, рельефные швы и свободный край.","image":"assets/shroud.png","sizes":["ONE SIZE"]}
,{"id":"noct","name":"NOCT","title":"Сапоги NOCT","price":21900,"image":"assets/noct.png","category":"accessories","sizes":["36","37","38","39","40"],"color":"Чёрный","material":"Натуральная кожа","fit":"Высокое голенище","description":"Острый мыс, тонкий каблук и мягкие складки у щиколотки."},{"id":"clasp","name":"CLASP","title":"Перчатки CLASP","price":5900,"image":"assets/clasp.png","category":"accessories","sizes":["S","M","L"],"color":"Чёрный","material":"Натуральная кожа","fit":"Без пальцев","description":"Открытые пальцы, серебристые люверсы и регулируемая застёжка."},{"id":"drape","name":"DRAPE","title":"Пояс-панель DRAPE","price":8900,"category":"accessories","sizes":["ONE SIZE"],"color":"Чёрный","material":"65% полиэстер, 35% вискоза","fit":"Регулируемый","description":"Две свободные панели добавляют движение поверх брюк.","image":"assets/drape.png"},{"id":"ivory","name":"IVORY","title":"Футболка IVORY","price":5900,"category":"top","sizes":["XS","S","M","L","XL"],"color":"Белый","material":"100% хлопок","fit":"Oversize","description":"Белый хлопок и серебристые люверсы по линии горловины.","image":"assets/ivory.png"},{"id":"bristle","name":"BRISTLE","title":"Ботинки BRISTLE","price":19900,"category":"accessories","sizes":["36","37","38","39","40","41"],"color":"Графит","material":"Искусственный мех / резиновая подошва","fit":"Объёмные","description":"Длинный ворс и массивная рельефная подошва.","image":"assets/bristle.png"},{"id":"pierce","name":"PIERCE","title":"Юбка PIERCE","price":10900,"category":"bottom","sizes":["XS","S","M","L"],"color":"Чёрный","material":"65% полиэстер, 35% вискоза","fit":"Мини / на запах","description":"Диагональ серебристых люверсов подчёркивает асимметричный крой.","image":"assets/pierce.png"},{"id":"rivet","name":"RIVET","title":"Чокер RIVET","price":3900,"category":"accessories","sizes":["ONE SIZE"],"color":"Чёрный","material":"Натуральная кожа / металл","fit":"Регулируемый","description":"Кожаная лента с серебристыми люверсами и пряжкой.","image":"assets/rivet.png"},{"id":"shade","name":"SHADE","title":"Кепка SHADE","price":4900,"category":"accessories","sizes":["ONE SIZE"],"color":"Чёрный","material":"100% хлопок","fit":"Регулируемый","description":"Скульптурные швы и единственная металлическая заклёпка.","image":"assets/shade.png"},{"id":"ember","name":"EMBER","title":"Гетры EMBER","price":7900,"category":"accessories","sizes":["ONE SIZE"],"color":"Чёрный","material":"Искусственный мех: 100% полиэстер","fit":"Эластичный верх","description":"Съёмный слой длинного ворса для новых пропорций.","image":"assets/ember.png"},{"id":"strata","name":"STRATA","title":"Брюки STRATA","price":14900,"category":"bottom","sizes":["XS","S","M","L","XL"],"color":"Чёрный","material":"Деним: хлопок; панель: полиэстер / вискоза","fit":"Широкие","description":"Выстиранный деним и строгая плиссированная панель в одной вещи.","image":"assets/strata.png"}];